[package]
name = "raylib-sys"
version = "0.9.2"
authors = ["DeltaPHC <phclem@protonmail.com>"]
license = "Zlib"
description = "Raw FFI bindings for Raylib"
documentation = "https://docs.rs/raylib-sys"
repository = "https://github.com/deltaphc/raylib-rs"
keywords = ["bindings", "raylib", "gamedev", "ffi"]
categories = ["external-ffi-bindings"]
edition = "2018"
build = "build.rs"

[build-dependencies]
bindgen = "^0.47"
reqwest = "^0.9"
tar = "0.4"
flate2 = "0.2"
cc = "1.0"
pkg-config = "0.3"

[features]
default = []
genbindings = []
bundled = []
